### ISSUE TITLE
Nothing in plugin interface

### ISSUE THREAD

**Issue by zhuoyun233** [ILadis/ts3-qs4sd#11]
Installed TeamSpeak3, logged in TS3 account and added bookmarks. But there's nothing in the plugin interface. Tried uninstall and install again, both TS3 and the plugin, still can't solve it. 
![IMG_1385](https://github.com/ILadis/ts3-qs4sd/assets/82555949/01b05aeb-68e1-4d10-85d8-f92f32332348)

**Comment by ILadis** [comment]
Which version of the plugin are you using? The plugin from the official store (1.1.3) is currently non functional. This is because the Flatpak application identifier has changed for TeamSpeak 3.

**Edit**:  
Version 1.1.4 is now available in the store. Please make sure to update. I assume that fixes your issue.
