### ISSUE TITLE
API Version not compatible

### ISSUE THREAD

**Issue by ThaMighty90** [ILadis/ts3-qs4sd#3]
Hi,

i just tried to install your plugin but i always get an error when teamspeak tries to load the plugin.

![image](https://github.com/ILadis/ts3-qs4sd/assets/30285364/fded29d8-6cc4-4e83-9c63-b51fc36687ac)

I tired with v0.4 and v0.5-dev of your plugin. my Teamspeak Version is 3.6.0.

Thanks in advance for your help.

**Comment by ILadis** [comment]
Thanks for reporting this issue!

This is happening due to the latest TeamSpeak version 3.6.0.  
I've published a new release version of the plugin, which should be compatible.

You can download this version [here](https://github.com/ILadis/ts3-qs4sd/releases/tag/v0.5). Please report back if this fixes the issue.

**Comment by Hellangel1987** [comment]
issue fixed with your new 0.5 Version

**Comment by ThaMighty90** [comment]
Issue is fixed
